apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "app.defaultLabels" . | indent 4 }}
  name: {{ .Release.Name }}-service
spec:
  ports:
    - port: 9000
      protocol: TCP
  selector:
    {{- include "app.matchLabels" . | indent 4 }}